export const KNOWLEDGE_POINTS = [
  {
    id: 'uv-remap',
    page: '/learn-uv-remap.html',
    title: '坐标居中：uv × 2 − 1',
    label: '坐标居中原理',
    icon: '📐',
    patterns: ['uv * 2.0 - 1.0', 'uv*2.0-1.0', '* 2.0 - 1.0', 'uv - 0.5', 'uv-0.5'],
  },
  {
    id: 'smoothstep',
    page: '/learn-smoothstep.html',
    title: 'smoothstep 平滑阶跃',
    label: 'smoothstep 原理',
    icon: '📈',
    patterns: ['smoothstep('],
  },
  {
    id: 'sdf-basics',
    page: '/learn-sdf-basics.html',
    title: 'SDF 有符号距离函数',
    label: 'SDF 基础',
    icon: '⭕',
    patterns: ['length(uv', 'length(p', '- radius', '- r;', '- r)'],
  },
  {
    id: 'sin-cos',
    page: '/learn-sin-cos.html',
    title: 'sin/cos 三角函数',
    label: 'sin/cos 波形',
    icon: '🌊',
    patterns: ['sin(', 'cos('],
  },
  {
    id: 'mix-blend',
    page: '/learn-mix-blend.html',
    title: 'mix 颜色混合与插值',
    label: 'mix 混合原理',
    icon: '🎨',
    patterns: ['mix('],
  },
  {
    id: 'dot-product',
    page: '/learn-dot-product.html',
    title: 'dot 点积运算',
    label: '点积原理',
    icon: '🔘',
    patterns: ['dot('],
  },
  {
    id: 'matrix-transform',
    page: '/learn-matrix-transform.html',
    title: '矩阵变换：旋转/缩放/剪切',
    label: '矩阵变换',
    icon: '🔄',
    patterns: ['mat2(', 'mat2 ', 'mat3(', 'mat3 '],
  },
  {
    id: 'polar-coords',
    page: '/learn-polar-coords.html',
    title: '极坐标：atan 与 length',
    label: '极坐标系',
    icon: '🎯',
    patterns: ['atan('],
  },
  {
    id: 'fract-repeat',
    page: '/learn-fract-repeat.html',
    title: 'fract 取小数与图案重复',
    label: 'fract 重复',
    icon: '🔁',
    patterns: ['fract('],
  },
  {
    id: 'color-blend',
    page: '/learn-color-blend.html',
    title: '颜色加减与光效叠加 (+= / *=)',
    label: '光斑与色彩算术',
    icon: '✨',
    patterns: ['+=', '*=', 'color +', 'color *', '-='], 
  },
];
