export const KNOWLEDGE_POINTS = [
  {
    id: 'aspect-ratio',
    page: '/learn-aspect-ratio.html',
    title: '宽高比校正',
    label: '为什么乘宽高比',
    icon: '📏',
    patterns: ['.x *= u_resolution.x / u_resolution.y', '.x *= u_resolution.x/u_resolution.y'],
  },
  {
    id: 'sdf-glow',
    page: '/learn-sdf-glow.html',
    title: 'SDF 辉光原理',
    label: 'exp(-abs(d)) 发光',
    icon: '💡',
    patterns: ['exp(-abs(d)', 'exp(-abs('],
  },
  {
    id: 'uv-normalize',
    page: '/learn-uv-normalize.html',
    title: 'UV 归一化：像素 → [0, 1]',
    label: '为什么除以分辨率',
    icon: '📍',
    patterns: ['gl_FragCoord.xy / u_resolution', 'gl_FragCoord / u_resolution'],
  },
  {
    id: 'uv-remap',
    page: '/learn-uv-remap.html',
    title: '坐标居中：uv × 2 − 1',
    label: '坐标居中原理',
    icon: '📐',
    patterns: ['uv * 2.0 - 1.0', 'uv*2.0-1.0', '* 2.0 - 1.0', 'uv - 0.5', 'uv-0.5'],
  },
  {
    id: 'smoothstep',
    page: '/learn-smoothstep.html',
    title: 'smoothstep 平滑阶跃',
    label: 'smoothstep 原理',
    icon: '📈',
    patterns: ['smoothstep('],
  },
  {
    id: 'sdf-basics',
    page: '/learn-sdf-basics.html',
    title: 'SDF 有符号距离函数',
    label: 'SDF 基础',
    icon: '⭕',
    patterns: ['length(uv', 'length(p', '- radius', '- r;', '- r)'],
  },
  {
    id: 'sin-cos',
    page: '/learn-sin-cos.html',
    title: 'sin/cos 三角函数',
    label: 'sin/cos 波形',
    icon: '🌊',
    patterns: ['sin(', 'cos('],
  },
  {
    id: 'mix-blend',
    page: '/learn-mix-blend.html',
    title: 'mix 颜色混合与插值',
    label: 'mix 混合原理',
    icon: '🎨',
    patterns: ['mix('],
  },
  {
    id: 'dot-product',
    page: '/learn-dot-product.html',
    title: 'dot 点积运算',
    label: '点积原理',
    icon: '🔘',
    patterns: ['dot('],
  },
  {
    id: 'matrix-transform',
    page: '/learn-matrix-transform.html',
    title: '矩阵变换：旋转/缩放/剪切',
    label: '矩阵变换',
    icon: '🔄',
    patterns: ['mat2(', 'mat2 ', 'mat3(', 'mat3 '],
  },
  {
    id: 'polar-coords',
    page: '/learn-polar-coords.html',
    title: '极坐标：atan 与 length',
    label: '极坐标系',
    icon: '🎯',
    patterns: ['atan('],
  },
  {
    id: 'fract-repeat',
    page: '/learn-fract-repeat.html',
    title: 'fract 取小数与图案重复',
    label: 'fract 重复',
    icon: '🔁',
    patterns: ['fract('],
  },
  {
    id: 'color-blend',
    page: '/learn-color-blend.html',
    title: '颜色加减与光效叠加 (+= / *=)',
    label: '光斑与色彩算术',
    icon: '✨',
    patterns: ['+=', '*=', 'color +', 'color *', '-='], 
  },
  {
    id: 'ndc-coords',
    page: '/learn-ndc-coords.html',
    title: 'NDC 标准化设备坐标',
    label: '屏幕 → NDC',
    icon: '🖱️',
    patterns: [],
  },
  {
    id: 'texture-sample',
    page: '/learn-texture-sample.html',
    title: '纹理采样 texture2D',
    label: '多 pass 纹理读写',
    icon: '🗂️',
    patterns: ['texture2D('],
  },
  {
    id: 'wave-equation',
    page: '/learn-wave-equation.html',
    title: '水面波动方程',
    label: '邻域采样求高',
    icon: '〰️',
    patterns: [],

  },
  {
    id: 'normal-map',
    page: '/learn-normal-map.html',
    title: '法线贴图扰动 UV',
    label: '反射偏移',
    icon: '🗺️',
    patterns: [],

  },
  {
    id: 'gpgpu-particles',
    page: '/learn-gpgpu-particles.html',
    title: 'GPGPU 粒子模拟',
    label: 'FBO 速度/位置 pass',
    icon: '✨',
    patterns: [],

  },
  {
    id: 'euler-integration',
    page: '/learn-gpgpu-particles.html',
    title: '欧拉积分',
    label: 'v += a·dt, p += v·dt',
    icon: '🏃',
    patterns: [],
  },
  {
    id: 'render-to-texture',
    page: '/learn-texture-sample.html',
    title: '渲染到纹理 RTT',
    label: '多 Pass ping-pong',
    icon: '🖼️',
    patterns: [],
  },
  {
    id: 'particle-life',
    page: '/learn-particle-life.html',
    title: '粒子生命周期',
    label: 'alpha 衰减与重生',
    icon: '💫',
    patterns: [],

  },
  {
    id: 'barrel-distortion',
    page: '/learn-barrel-distortion.html',
    title: '桶形畸变 Barrel Distortion',
    label: '径向 UV 偏移',
    icon: '🔭',
    patterns: [],

  },
  {
    id: 'blend-screen',
    page: '/learn-blend-screen.html',
    title: 'Screen 滤色混合',
    label: '1 − (1−a)(1−b)',
    icon: '💡',
    patterns: [],

  },
  {
    id: 'noise-texture',
    page: '/learn-noise-texture.html',
    title: '噪声纹理采样',
    label: '雾与氛围',
    icon: '🌫️',
    patterns: [],

  },
];
